name: Publish on GitHub, CurseForge & Modrinth

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-pre.[0-9]+'

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  preparations:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        uses: tj-actions/branch-names@v7.0.5
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}

  build:
    needs: preparations
    runs-on: ubuntu-latest

    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" clean build

      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          loaders: |
            fabric
            forge

          curseforge-id: 935081
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          modrinth-id: usDxEvVr
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

          github-tag: "${{ needs.preparations.outputs.version }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          github-prerelease: true

          name: "AddEmAll ${{ needs.preparations.outputs.version }} for Minecraft 1.19.2"
          version: "${{ needs.preparations.outputs.version }}"
          changelog-file: CHANGELOG.md

          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"

          files: |
            +(Forge|Fabric)/build/libs/*[0-9].jar