name: Publish release on GitHub, CurseForge & Modrinth

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  GITLAB_URL: https://git.griefed.de
  GITLAB_PROJECT_ID: 119

permissions:
  contents: write

jobs:
  preparations:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        uses: tj-actions/branch-names@v7.0.5
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}


      # GET RELEASE INFO
      - name: Get Release Info
        run: |
          curl --header \
          'PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}' \
          '${{ env.GITLAB_URL }}/api/v4/projects/${{ env.GITLAB_PROJECT_ID }}/releases/${{ needs.preparations.outputs.version }}' >> version.json

      # GET DESCRIPTION
      - name: Extract version changelog
        uses: sergeysova/jq-action@v2.3.0
        id: description
        with:
          cmd: "jq .description version.json -r | sed -e 's/\\n/\\n/g' > description.txt"
          multiline: true

      - name: Dafuq # Otherwise we wouldn't be able to work with the file. Because reasons...
        run: sudo chown $USER description.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.preparations.outputs.version }}
          name: Pre-Release ${{ needs.preparations.outputs.version }}
          body_path: description.txt
          draft: false

  build:
    needs: preparations
    strategy:
      matrix:
        include:
          - platform: forge
            name: Forge
          - platform: fabric
            name: Fabric
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew -Pversion="${{ needs.preparations.outputs.version }}" clean blockAndItemCodeGen build

      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          loaders: |
            ${{ matrix.platform }}

          curseforge-id: 935081
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          modrinth-id: usDxEvVr
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"
          modrinth-unfeature-mode: loader-any

          github-tag: "${{ needs.preparations.outputs.version }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

          name: "AddEmAll ${{ matrix.name }} ${{ needs.preparations.outputs.version }} for Minecraft 1.19.2"

          game-versions: "${{ env.MINECRAFT_VERSION }}"
          java: "${{ env.JAVA_VERSION }}"

          files: |
            ${{ matrix.name }}/build/libs/*[0-9].jar
